### ISSUE TITLE
GSL 1.16 build issues

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#97]
```
$ ./Build
Building Math-GSL
Processing 1.16 XS files, GSL 1.16 (via gsl-config) at /usr/local
Compiler   = Ubuntu clang version 3.5.0-4ubuntu2 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

ccflags    = -I/usr/local/include -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wno-unused-function -Wno-unused-value -Wno-unused-function -Wno-unused-variable -Wno-gnu -g -fPIC -fno-omit-frame-pointer
ldflags    = -shared -L/usr/local/lib -lgsl -lgslcblas -lm -fPIC -fno-omit-frame-pointer
xs/BSpline_wrap.1.16.c:3538:23: error: no member named 'A' in 'gsl_bspline_workspace'
    if (arg1) (arg1)->A = arg2;
              ~~~~~~  ^
xs/BSpline_wrap.1.16.c:3568:38: error: no member named 'A' in 'gsl_bspline_workspace'
    result = (gsl_matrix *) ((arg1)->A);
                             ~~~~~~  ^
xs/BSpline_wrap.1.16.c:3603:23: error: no member named 'dB' in 'gsl_bspline_workspace'
    if (arg1) (arg1)->dB = arg2;
              ~~~~~~  ^
xs/BSpline_wrap.1.16.c:3633:38: error: no member named 'dB' in 'gsl_bspline_workspace'
    result = (gsl_matrix *) ((arg1)->dB);
                             ~~~~~~  ^
xs/BSpline_wrap.1.16.c:4207:61: error: too few arguments to function call, expected 5, have 4
    result = (int)gsl_bspline_deriv_eval(arg1,arg2,arg3,arg4);
                  ~~~~~~~~~~~~~~~~~~~~~~                    ^
/usr/local/include/gsl/gsl_bspline.h:101:1: note: 'gsl_bspline_deriv_eval' declared here
int
^
xs/BSpline_wrap.1.16.c:4281:79: error: too few arguments to function call, expected 7, have 6
    result = (int)gsl_bspline_deriv_eval_nonzero(arg1,arg2,arg3,arg4,arg5,arg6);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                              ^
/usr/local/include/gsl/gsl_bspline.h:108:1: note: 'gsl_bspline_deriv_eval_nonzero' declared here
int
^
6 errors generated.
error building .o file from 'xs/BSpline_wrap.1.16.c' at inc/GSLBuilder.pm line 342.
```

**Comment by leto** [comment]
Ok, this is what I have figured out.

GSL 2.0 merged `bspline_deriv_workspace` into `bspline_workspace`, which also means that `gsl_bspline_deriv_eval` and `gsl_bspline_deriv_eval_nonzero` take one less argument each. The `gsl_bspline_deriv.*` functions were added in GSL 1.15.

This means when we generate a CPAN distribution, we are using the new 4-arg form of `gsl_bspline_deriv_eval` for GSL 1.15 and GSL 1.16, which is incorrect. Previous CPAN distributions were generated with at most GSL 1.16, which had the old 5-arg form of `gsl_bspline_deriv_eval` and so Did The Right Thing.

Currently Math::GSL is not compatible with GSL 1.15 or 1.16, which is 💩 . We could fib and move `gsl_bspline_deriv.*` to the 2.0 list in `inc/ver2func`, which should get us compatible with 1.15 and 1.16 again at the expense of Bspline derivatives not working in 1.15 + 1.16. That seems like a net win.

Alternately we could do some SWIG/XS shenanigans to fix it properly, but I am unsure exactly how to do that and I not sure it is worth it to get a small feature in an old release of GSL working.

**Comment by ambs** [comment]
As I do not have much time to help, please choose the easier way.
But as I will need four PRs for HacktoberFest,  who knows I can do one for Math::GSL

**Comment by leto** [comment]
Making progress, now we have:

```
xs/Interp_wrap.1.16.c:2165:5: error: use of undeclared identifier 'gsl_interp_steffen'; did you mean 'gsl_interp_cspline'?
    gsl_interp_steffen = (gsl_interp_type *)(argp);
    ^~~~~~~~~~~~~~~~~~
    gsl_interp_cspline
/usr/local/include/gsl/gsl_interp.h:77:33: note: 'gsl_interp_cspline' declared here
GSL_VAR const gsl_interp_type * gsl_interp_cspline;
                                ^
xs/Interp_wrap.1.16.c:2174:28: error: use of undeclared identifier 'gsl_interp_steffen'; did you mean 'gsl_interp_free'?
  sv_setiv(SvRV(sv),PTR2IV(gsl_interp_steffen));
                           ^~~~~~~~~~~~~~~~~~
                           gsl_interp_free
```

**Comment by leto** [comment]
I navigated past these errors and will release 0.39 soon which should support 1.16 - 2.2.1 nicely and partial support for 1.15. I have 1.15 working nicely on Linux+GSL 1.15 but we get failures from Travis CI.
